
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wang?serverTimezone=CST&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
